# ======================================================================
# 19 Jekyll yapılandırması
# ======================================================================

# kalıcı adresler (lütfen bu ayara dokunmayın)
permalink: /:categories:title

# sözdizimi renklendirmesi
pygments: true

# ----------------------------------------------------------------------
# temel parametreler
# 
# bu parameterleri doğrudan "site" uzayına yerleştiriyoruz
# ----------------------------------------------------------------------

# github hesap adı (ör. roktas)
account: zaman

# github organizasyonu (ör. 19)
organization: 19

# bu siteyi üreten github deposu (ör. roktas.github.com)
repository: zaman.github.com

# üretilen sitenin web adresi ne?  ör. "http://foo.github.com/bar".
url: http://zaman.github.com

# sitede kullanılan ortak "dijital varlıklar"ın (ör. görseller, logolar)
# adresi.  dikkat:
#
# - site görünümüne ait görsel ve javascript dosyaları chrome dizininde
# - içeriklerde kullanılan resim ve görsel için images dizininde
# - bu adresi mutlak formda tanımlayın.  örnekler:
#
# 	/assets
# 	http://00010011.github.com/assets
assets: /chrome

# ----------------------------------------------------------------------
# site parametreleri
# 
# kalan tüm parameterleri "site.param" uzayına koyuyoruz
# ----------------------------------------------------------------------
param:
        # --------------------------------------------------------------
        # kişisel parametreler
        # --------------------------------------------------------------
        # kısa kullanıcı adı (ör. roktas)
        # dikkat!  sisteminizdeki ad github hesabından farklı olabilir
        name: zaman
        # tam kullanıcı adı (ör. Recai Oktaş)
        fullname: zafer amanvermez
        # email adresi (ör. roktas@bil.omu.edu.tr)
        email: zaman@bil.omu.edu.tr
        # sitede kullanılacak tepe web adresi (ör. http://roktas.me)
        # dikkat!  bu değişkeni "url" ile karıştırmayın!
        web: http://00010011.github.com
        # ünvan (ör. Bilgisayar Mühendisliği Öğrencisi)
        title: <a href="http://ondokuz.biz/">19</a> üyesi
        # GnuPG kısa parmak izi (ör. DEADBEEF)
        gpg: ~
        # twitter adresi (ör. http://19.statusnet/roktas)
        twitter: http://19.status.net/zaman
        # flick adresi (ör. http://flickr.com/photos/roktas)
        flickr: zamanvermez
        # facebook adresi (ör. http://facebook.com/roktas)
        facebook: zamanvermez
        # özet akışı adresi (ör. http://feeds.feedburner.com/roktas)
        feed: zamanvermez

        # --------------------------------------------------------------
        # sitede kullanılan bazı metinler
        # --------------------------------------------------------------
        section0: Web Günlüğü
        section1: Makaleler
        section2: İlkeler
        section7: Çeşitli
        section9: Notlar

        # --------------------------------------------------------------
        # ekstra özellik parametreleri
        #
        # bu değişkenler tanımlanmazsa (~ kullanın) öntanımlı sitede
        # ilgili özellik bulunmayacaktır (örneğin: disqus)
        #
        # dikkat!  değişkenin tanımlı olmaması için ~ değeri verin
        # --------------------------------------------------------------
        # girdi arşivi
        archive: Son Girdiler
        # ilişkili girdiler
        related: Diğer Girdiler
        # logo (ör. http://00010011.github.com/assets/19/19-normal-128x128.png)
        logo: /chrome/19/19-normal-128x128.png
        # google arama kutusu
        google: true
        # google analytics takip numarası (ör. UA-1234567-8
        googleanalyticsid: ~
        # sayfa yorumları için disqus site kaydı (ör. roktas)
        disqus: ~
        # GitHub şerit metni (ör. GitHub'dayım)
        ribbon: GitHub'dayım
