#!/bin/sh

# Jekyll sunucusunu localhost'ta çalıştır.

THISDIR="${0%/*}"
. $THISDIR/../util.sh

cat >&2 <<EOF
Jekyll bu konsolda sunucu kipinde çalıştırılacak.  Siteyi görüntülemek
için tarayıcıda şu adrese girin:

	http://localhost:4000

Lütfen sitede düzenleme yapmak için başka bir konsol açın.  Her düzenlemeden
sonra site otomatik olarak güncellenecektir.  Değişiklikleri görmek için
tarayıcıda açılı olan sayfayı tekrar yükleyin.  Üretilen dosyalar "_site"
dizinindedir.

DİKKAT!  "_config.yml" dosyasında yaptığınız değişiklikler otomatik olarak
etkinleşmeyecektir.  Bu dosyada değişiklik yapmışsanız bu betiği Ctrl-C ile
sonlandırıp tekrar çalıştırın.


EOF

exec jekyll --rdiscount --url http://localhost:4000 --server --auto
